//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseTracker.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpenseTracker.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added expense category..
        /// </summary>
        public static string AddCategorySuccessful {
            get {
                return ResourceManager.GetString("AddCategorySuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Expense.
        /// </summary>
        public static string AddExpense {
            get {
                return ResourceManager.GetString("AddExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this record?.
        /// </summary>
        public static string AreYouSureYouWantToDeleteThisRecord {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteThisRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save the changes?.
        /// </summary>
        public static string AreYouSureYouWantToSaveTheChanges {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToSaveTheChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Expense Category.
        /// </summary>
        public static string ChooseExpenseCategory {
            get {
                return ResourceManager.GetString("ChooseExpenseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Selected.
        /// </summary>
        public static string ClearSelected {
            get {
                return ResourceManager.GetString("ClearSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Edit.
        /// </summary>
        public static string ConfirmEdit {
            get {
                return ResourceManager.GetString("ConfirmEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Range.
        /// </summary>
        public static string DateRange {
            get {
                return ResourceManager.GetString("DateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted expense category..
        /// </summary>
        public static string DeleteCategorySuccessful {
            get {
                return ResourceManager.GetString("DeleteCategorySuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting Expense Record.
        /// </summary>
        public static string DeletingExpenseRecord {
            get {
                return ResourceManager.GetString("DeletingExpenseRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully edited expense category..
        /// </summary>
        public static string EditCategorySuccessful {
            get {
                return ResourceManager.GetString("EditCategorySuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Summary Report.
        /// </summary>
        public static string MonthlySummaryReport {
            get {
                return ResourceManager.GetString("MonthlySummaryReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Expenses.
        /// </summary>
        public static string RecentExpenses {
            get {
                return ResourceManager.GetString("RecentExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully restored expense category..
        /// </summary>
        public static string RestoreCategorySuccessful {
            get {
                return ResourceManager.GetString("RestoreCategorySuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        public static string Sample {
            get {
                return ResourceManager.GetString("Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Expense Record.
        /// </summary>
        public static string UpdatingExpenseRecord {
            get {
                return ResourceManager.GetString("UpdatingExpenseRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Chart.
        /// </summary>
        public static string ViewChart {
            get {
                return ResourceManager.GetString("ViewChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View List.
        /// </summary>
        public static string ViewList {
            get {
                return ResourceManager.GetString("ViewList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Summary.
        /// </summary>
        public static string WeeklySummary {
            get {
                return ResourceManager.GetString("WeeklySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Summary Report.
        /// </summary>
        public static string WeeklySummaryReport {
            get {
                return ResourceManager.GetString("WeeklySummaryReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weeks In Month.
        /// </summary>
        public static string WeeksInMonth {
            get {
                return ResourceManager.GetString("WeeksInMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weeks In Year.
        /// </summary>
        public static string WeeksInYear {
            get {
                return ResourceManager.GetString("WeeksInYear", resourceCulture);
            }
        }
    }
}
